### ISSUE TITLE
Documentation Issues

### ISSUE THREAD

**Issue by gitcnd** [pmqs/IO-Compress#2]
There's no example showing how to use this as a stream filter (glaring omission, this being the purpose of the module!).

There's no example showing how to use [,OPTS] either - very confusing.

How does a stream get a filename?  How are normal everyday users supposed to unzip files that have no name?

You probably want to add something like this, after you modify the below to put a filename (I suggest "output.csv") into the zip:-

	echo mydata,tostore | perl -MIO::Compress::Zip -e 'IO::Compress::Zip::zip \*STDIN=>\*STDOUT,AutoClose=>1; ' >output.zip  

The above, FYI, does:-
	# unzip -l output.zip 
	Archive:  output.zip
	  Length     Date   Time    Name
	 --------    ----   ----    ----
	       15  07-06-19 21:56   
	 --------                   -------
	       15                   1 file

(Note the missing name)

**Comment by gitcnd** [comment]
I figured it out - you doc REALLY needs more examples, and a good deal of unambiguation/clarity-work - eg: with your description of what "Name" means - the term "zip filename" *obviously* means the name of the zip file (eg output.zip) to everyone except the code author - so this sentence means nothing to everyone except the code author: "Stores the contents of $string in the zip filename header field."  (modules users have no idea what a "header field" is)

`echo mydata,tostore | perl -e 'use IO::Compress::Zip("zip");zip \*STDIN=>\*STDOUT,AutoClose=>1,Name=>"output.csv"; ' >/output.zip`

**Comment by pmqs** [comment]
Addressed in e1fd0d4eda0a8496981cbd83ad06906f4ae586a5
