### ISSUE TITLE
Missing dependency Compress::Raw::Zlib v2.095

### ISSUE THREAD

**Issue by GeJ** [pmqs/IO-Compress#22]
The latest version of IO::Compress expects (per Makefile.PL) to have Compress::Raw::Zlib at the same version, but at the time of this writing, the latest version for Compress::Raw::Zlib is v2.094 dated July 13th.

Thanks for your work on these modules.

**Comment by pmqs** [comment]
my fault. I forgot to upload Compress::Raw::Zlib 2.095 to CPAN along with all the other IO::Compress  modules. Should be sorted now.

Thanks for taking the time to report this.
Paul
