### ISSUE TITLE
Tests hanging on Windows Quadmath Perl build

### ISSUE THREAD

**Issue by pmqs** [pmqs/IO-Compress#29]
Issue report copied from [Perl Monks](https://www.perlmonks.org/?node_id=3333;parent=11128612) by @sisyphus

> Not sure that anyone here is particularly interested in this, but I'll mention it anyway that, as of the release (on 20.01.2021) of perl-5.33.6, it's possible to build perl on MS Windows with an NV type of __float128.
> And it has become a little easier in 5.33.7 with a change to GNUmakefile that removed the need for a somewhat cumbersome configuration argument.
> With the release of perl-5.22.0, the NV type of long double was enabled on Windows, and now we finally get the additional option of having the __float128 NV type.
> All of this does, of course, rely on using mingw-w64 ports of gcc to build your Windows perl.
> 
> I think that many of us, accustomed to simply using Strawberry Perl, don't realize just how easy it is to build perl from source on Windows.
> Strawberry Perl, itself, does provide us with the toolchain that's capable of building any recent version of perl (including blead releases) from source.
> The latest blead source can be obtained with:
>
> `$ git clone https://github.com/sisyphus/perl5.git blead_clone`
> 
> or the perl-5.33.7 development tarball is available from:
>
> `https://cpan.metacpan.org/authors/id/R/RE/RENEEB/perl-5.33.7.tar.gz`
> 
> Then, I place my C:\_64\strawberry-5.32.0\c\bin folder at the beginning of my PATH, and I have all that I need to build perl.
> Simply cd to the perl source's win32 folder and run:
>
> `gmake INST_TOP=C:\bleadstraw CCHOME=C:\_64\strawberry-5.32.0\c CCTYPE=GCC I_QUADMATH=define USE_QUADMATH=define test`
>
> Then, to install perl into the location specified by INST_TOP, just run:
>
> `gmake INST_TOP=C:\bleadstraw CCHOME=C:\_64\strawberry-5.32.0\c CCTYPE=GCC I_QUADMATH=define USE_QUADMATH=define install`
> 
> And that's it - in C:\bleadstraw I now have a Windows perl that has __float128 as its NV.
> 
> You may want to alter INST_TOP, and you probably need to alter CCHOME which should specify the full path to gcc's bin directory.
> NOTE that CCHOME does not include "\bin". (Failure to get CCHOME right will cause some test failures, but will not affect the perl that has been built.)
> 
> If you want to do a 'long double' build instead, you would just remove the 2 gmake arguments that include the string "QUADMATH", and insert the USE_LONG_DOUBLE=define argument.
> If you don't request either a 'long double' or a 'quadmath' build, then the nvtype will be 'double'.
> 
> If you're using a 32-bit compiler, you'll also need to insert the argument WIN64=undef, and you might also want to add the argument USE_64_BIT_INT=define if you want 64-bit integers and pointers.
> With 64-bit compilers, perl's integer and pointer will inevitably be 64-bit.
> 
> I think that covers the most commonly exercised options ... but you'll find additional options laid out in the GNUmakefile.
> 
> **I don't know if it's a general issue, but (on 64-bit builds only) there's usually a couple of test scripts in cpan/IO-Compress/t that hang for me .**
> **It's generally (but not always) the same test scripts that hang, and it has been happening for a few years. In perl-5.33.7, I'm finding that the problem has moved to a different couple of files.**
> The Strawberry project have never, to my knowledge, complained about such an issue - so I'm hoping that it's just something in my particular environment.
> It would be nice to find out if it is "just me".
> It's quite annoying - I have to kill these hangs using process explorer in order to get the test suite to run to completion. (Killing them with Ctrl-C kills the entire 'gmake test' process.)
> These test scripts have always passed when run outside of the testing harness, and they've also passed even when I've run make test in the cpan/IO-Compress folder.
> There's also the same thing happening in the cpan/IPC-Cmd tests with t/01_IPC-Cmd.t.
> If I can find any evidence that it's also an issue for others then I'll try to get it fixed.
> 
> Oh, one last thing - if you build a 32-bit perl with I_QUADMATH=define USE_QUADMATH=define but without USE_64_BIT_INT=define, then expect some failing tests in Math::BigFloat due to a Math::BigInt::Calc bug.
> This issue has been reported, with a proposed simple fix to Calc.pm.
> 
> Cheers,
> Rob

**Comment by pmqs** [comment]
Tried to reproduce  with this on a Windows 10 box

`gmake INST_TOP=C:\bleadstraw CCHOME=C:\_64\strawberry-5.32.0\c CCTYPE=GCC I_QUADMATH=define USE_QUADMATH=define`

all tests s passed

```
../cpan/IO-Compress/t/000prereq.t .................................... ok
../cpan/IO-Compress/t/001bzip2.t ..................................... ok
../cpan/IO-Compress/t/001zlib-generic-deflate.t ...................... ok
../cpan/IO-Compress/t/001zlib-generic-gzip.t ......................... ok
../cpan/IO-Compress/t/001zlib-generic-rawdeflate.t ................... ok
../cpan/IO-Compress/t/001zlib-generic-zip.t .......................... ok
../cpan/IO-Compress/t/002any-deflate.t ............................... ok
../cpan/IO-Compress/t/002any-gzip.t .................................. ok
../cpan/IO-Compress/t/002any-rawdeflate.t ............................ ok
../cpan/IO-Compress/t/002any-transparent.t ........................... ok
../cpan/IO-Compress/t/002any-zip.t ................................... ok
../cpan/IO-Compress/t/004gziphdr.t ................................... ok
../cpan/IO-Compress/t/005defhdr.t .................................... ok
../cpan/IO-Compress/t/006zip.t ....................................... ok
../cpan/IO-Compress/t/011-streamzip.t ................................ ok
../cpan/IO-Compress/t/01misc.t ....................................... ok
../cpan/IO-Compress/t/020isize.t ..................................... skipped: Lengthy Tests Disabled
../cpan/IO-Compress/t/050interop-gzip.t .............................. ok
../cpan/IO-Compress/t/100generic-bzip2.t ............................. ok
../cpan/IO-Compress/t/100generic-deflate.t ........................... ok
../cpan/IO-Compress/t/100generic-gzip.t .............................. ok
../cpan/IO-Compress/t/100generic-rawdeflate.t ........................ ok
../cpan/IO-Compress/t/100generic-zip.t ............................... ok
../cpan/IO-Compress/t/101truncate-bzip2.t ............................ skipped: Lengthy Tests Disabled
../cpan/IO-Compress/t/101truncate-deflate.t .......................... skipped: Lengthy Tests Disabled
../cpan/IO-Compress/t/101truncate-gzip.t ............................. skipped: Lengthy Tests Disabled
../cpan/IO-Compress/t/101truncate-rawdeflate.t ....................... skipped: Lengthy Tests Disabled
../cpan/IO-Compress/t/101truncate-zip.t .............................. skipped: Lengthy Tests Disabled
../cpan/IO-Compress/t/102tied-bzip2.t ................................ ok
../cpan/IO-Compress/t/102tied-deflate.t .............................. ok
../cpan/IO-Compress/t/102tied-gzip.t ................................. ok
../cpan/IO-Compress/t/102tied-rawdeflate.t ........................... ok
../cpan/IO-Compress/t/102tied-zip.t .................................. ok
../cpan/IO-Compress/t/103newtied-bzip2.t ............................. ok
../cpan/IO-Compress/t/103newtied-deflate.t ........................... ok
../cpan/IO-Compress/t/103newtied-gzip.t .............................. ok
../cpan/IO-Compress/t/103newtied-rawdeflate.t ........................ ok
../cpan/IO-Compress/t/103newtied-zip.t ............................... ok
../cpan/IO-Compress/t/104destroy-bzip2.t ............................. ok
../cpan/IO-Compress/t/104destroy-deflate.t ........................... ok
../cpan/IO-Compress/t/104destroy-gzip.t .............................. ok
../cpan/IO-Compress/t/104destroy-rawdeflate.t ........................ ok
../cpan/IO-Compress/t/104destroy-zip.t ............................... ok
../cpan/IO-Compress/t/105oneshot-bzip2.t ............................. ok
../cpan/IO-Compress/t/105oneshot-deflate.t ........................... ok
../cpan/IO-Compress/t/105oneshot-gzip.t .............................. ok
../cpan/IO-Compress/t/105oneshot-gzip-only.t ......................... ok
../cpan/IO-Compress/t/105oneshot-rawdeflate.t ........................ ok
../cpan/IO-Compress/t/105oneshot-zip.t ............................... ok
../cpan/IO-Compress/t/105oneshot-zip-bzip2-only.t .................... ok
../cpan/IO-Compress/t/105oneshot-zip-only.t .......................... ok
../cpan/IO-Compress/t/105oneshot-zip-store-only.t .................... skipped: Lengthy Tests Disabled
../cpan/IO-Compress/t/106prime-bzip2.t ............................... skipped: Lengthy Tests Disabled
../cpan/IO-Compress/t/106prime-deflate.t ............................. skipped: Lengthy Tests Disabled
../cpan/IO-Compress/t/106prime-gzip.t ................................ skipped: Lengthy Tests Disabled
../cpan/IO-Compress/t/106prime-rawdeflate.t .......................... skipped: Lengthy Tests Disabled
../cpan/IO-Compress/t/106prime-zip.t ................................. skipped: Lengthy Tests Disabled
../cpan/IO-Compress/t/107multi-bzip2.t ............................... ok
../cpan/IO-Compress/t/107multi-deflate.t ............................. ok
../cpan/IO-Compress/t/107multi-gzip.t ................................ ok
../cpan/IO-Compress/t/107multi-rawdeflate.t .......................... ok
../cpan/IO-Compress/t/107multi-zip.t ................................. ok
../cpan/IO-Compress/t/107multi-zip-only.t ............................ ok
../cpan/IO-Compress/t/108anyunc-bzip2.t .............................. ok
../cpan/IO-Compress/t/108anyunc-deflate.t ............................ ok
../cpan/IO-Compress/t/108anyunc-gzip.t ............................... ok
../cpan/IO-Compress/t/108anyunc-rawdeflate.t ......................... ok
../cpan/IO-Compress/t/108anyunc-transparent.t ........................ ok
../cpan/IO-Compress/t/108anyunc-zip.t ................................ ok
../cpan/IO-Compress/t/109merge-deflate.t ............................. ok
../cpan/IO-Compress/t/109merge-gzip.t ................................ ok
../cpan/IO-Compress/t/109merge-rawdeflate.t .......................... ok
../cpan/IO-Compress/t/109merge-zip.t ................................. skipped: not implemented yet
../cpan/IO-Compress/t/110encode-bzip2.t .............................. ok
../cpan/IO-Compress/t/110encode-deflate.t ............................ ok
../cpan/IO-Compress/t/110encode-gzip.t ............................... ok
../cpan/IO-Compress/t/110encode-rawdeflate.t ......................... ok
../cpan/IO-Compress/t/110encode-zip.t ................................ ok
../cpan/IO-Compress/t/111const-deflate.t ............................. ok
../cpan/IO-Compress/t/112utf8-zip.t .................................. ok
../cpan/IO-Compress/t/999pod.t ....................................... skipped: Test::Pod 1.00 required for testing POD
../cpan/IO-Compress/t/cz-01version.t ................................. ok
../cpan/IO-Compress/t/cz-03zlib-v1.t ................................. ok
../cpan/IO-Compress/t/cz-06gzsetp.t .................................. ok
../cpan/IO-Compress/t/cz-08encoding.t ................................ ok
../cpan/IO-Compress/t/cz-14gzopen.t .................................. ok
../cpan/IO-Compress/t/globmapper.t ................................... ok
```

**Comment by sisyphus** [comment]
I'll update this with better information later today.
I just want to point out that this issue of mine is specific to 64-bit mingw-w64 ports of gcc, but it's NOT specific to the quadmath build.
I hit exactly the same issue when building with a 64-bit compiler, irrespective of nvtype. (I've updated my perlmonks post to make this clearer.)

**Comment by pmqs** [comment]
> I'll update this with better information later today.

Thanks

> I just want to point out that this issue of mine is specific to 64-bit mingw-w64 ports of gcc, but it's NOT specific to the quadmath build.
> I hit exactly the same issue when building with a 64-bit compiler, irrespective of nvtype. (I've updated my perlmonks post to make this clearer.)

Aaah, OK.

**Comment by sisyphus** [comment]
The attached setup.txt is just recording the first steps I took when I opened a new cmd.exe shell .
Initially, there's no 'perl' and no 'gcc' available.
I then insert C:\_64\strawberry-5.32.0\c\bin at the beginning of the PATH.
We then see that there's still no 'perl' available. (Of course, I don't need 'perl', anyway.
But the <code>gcc -v</code> output shows that we have a 64-bit build of gcc-8.3.0 at our disposal.

Having reached that stage, I've then dumped all of the environment variables and their settings into the attached env_var.txt.

I built both 5.33.6 and 5.33.7 because they're behaving a little differently - and perhaps there's something meaningful in those differences.

I built both of those perls with the same gmake command (except that I used a different INST_TOP so that I could install them into separate locations, if I so want.
(I still haven't tested to see whether I need to actually specify a setting for INST_TOP at the 'gmake test' stage. I suspect that could be delayed until the 'gmake install' step.)

The command I used to build and test perl was:
gmake INST_TOP=C:\bleadstraw-5.33.x CCHOME=C:\_64\strawberry-5.32.0\c CCTYPE=GCC test

The files test_report-5.33.6.txt and test_report-5.33.7.txt provide the test reports for the respective builds.
All you probably need to look at is the "Test Summary Report" at the end of both of those files - but I've also provided copy'n'pastes of the pertinent parts of the test suite as it ran.

Where to now ?

(It's now 11.59 pm over here, so I've fulfilled my promise to send this off "later today" ;-)

[setup.txt](https://github.com/pmqs/IO-Compress/files/6022059/setup.txt)
[env_var.txt](https://github.com/pmqs/IO-Compress/files/6022066/env_var.txt)
[test_report-5.33.6.txt](https://github.com/pmqs/IO-Compress/files/6022068/test_report-5.33.6.txt)
[test_report-5.33.7.txt](https://github.com/pmqs/IO-Compress/files/6022073/test_report-5.33.7.txt)

**Comment by pmqs** [comment]
All of the failing IO-Compress tests have the same thing in common - they are reading data from STDIN. I remember having trouble with STDIN on Windows when I wrote this code. In fact https://github.com/Perl/perl5/issues/8502 is still open. 

Tried rebuilding again on my Windows 10 setup - not seeing IO-Compress failures. Wonder if this is a Windows 7 issue. 

If you like I can make the failing IO-Compress tests skippable if a env variable is set?

Thanks for staying up late :-)

**Comment by sisyphus** [comment]
It just seems very odd that the 2 test files that hang in perl-5.33.6 (and earlier) are fine in perl-5.33.7 ... and that the 2 test files that hang in perl-5.33.7 are fine in perl-5.33.6 (and earlier).
Also odd that this happens without any changes having been made to the IO-Compress distro, AFAICS.

It also seems strange that if I cd to the cpan/IO-Compress folder and run <code>gmake test</code> then all is fine.
But if I run the same command from the win32 folder, then I experience the hanging when the process gets to running the IO-Compress tests.
Admittedly, the <code>gmake test</code> that gets run from cpan/IO-Compress seems to generate a different command to the one generated from inside the Win32 folder.

This is an issue that arose for me about 8-10 years ago, I reckon. I raised it (probably on p5p mailing list) and, shortly thereafter, it disappeared.
But then it started coming back intermittently - and it has been a permanent feature of my perl builds for probably the last 3 or 4 years.

Anyway, I think that enabling the skipping of those tests (via an environment variable) would be very useful for my purposes.
My builds are scripted and, after <code>gmake test</code> has terminated, I could always run the IO-Compress tests by having the script turn off the environment variable, cd to cpan/IO-Compress, and run <code>gmake test</code> from there.
At least I then get to verify that there's nothing amiss within the normal operating environment.

I wonder if this issue exists on Windows 8.

**Comment by pmqs** [comment]
> It just seems very odd that the 2 test files that hang in perl-5.33.6 (and earlier) are fine in perl-5.33.7 ... and that the 2 test files that hang in perl-5.33.7 are fine in perl-5.33.6 (and earlier).
> Also odd that this happens without any changes having been made to the IO-Compress distro, AFAICS.

Correct - the IO-Compress code is in maintenance mode these days. The changes made over the last few years have been mostly superficial.

> It also seems strange that if I cd to the cpan/IO-Compress folder and run `gmake test` then all is fine.
> But if I run the same command from the win32 folder, then I experience the hanging when the process gets to running the IO-Compress tests.
> Admittedly, the `gmake test` that gets run from cpan/IO-Compress seems to generate a different command to the one generated from inside the Win32 folder.
> 
> This is an issue that arose for me about 8-10 years ago, I reckon. I raised it (probably on p5p mailing list) and, shortly thereafter, it disappeared.
> But then it started coming back intermittently - and it has been a permanent feature of my perl builds for probably the last 3 or 4 years.

Windows development isn't my thing so unless the issue is very straightforward I struggle. The seemingly random nature of the failures would suggest a race condition if this was a multi-threaded application, but is isn't.

> Anyway, I think that enabling the skipping of those tests (via an environment variable) would be very useful for my purposes.
> My builds are scripted and, after `gmake test` has terminated, I could always run the IO-Compress tests by having the script turn off the environment variable, cd to cpan/IO-Compress, and run `gmake test` from there.
> At least I then get to verify that there's nothing amiss within the normal operating environment.

OK. I'll put that together.

**Comment by pmqs** [comment]
Code checked into GitHub. To disable STDIN tests set the environment variable `IO_COMPRESS_SKIP_STDIN_TESTS` to 1. Next release will have this icluded.

**Comment by sisyphus** [comment]
Thanks for that. It will simplify things considerably for me.

**Comment by pmqs** [comment]
Uploaded IO-Compress 2.102 to CPAN with this fix
