### ISSUE TITLE
WeakDecrypt should not be listed in MANIFEST

### ISSUE THREAD

**Issue by gregoa** [pmqs/IO-Compress#39]
The release tarball on the CPAN for 2.103 contains a new file `lib/IO/Compress/Zip/WeakDecrypt.pm` which

* is not in git
* has an interesting license comment at the top
* doesn't seem to be used by the other modules
* needs Data::Peek which is not mentioned in the metadata

I'm a bit confused :)

**Comment by pmqs** [comment]
Hey @gregoa 

That file is still a work-in-progress that shouldn't have been included that with the release.

**Comment by pmqs** [comment]
Fixed in IO-Compress 2.104

**Comment by gregoa** [comment]
On Sat, 09 Apr 2022 13:59:43 -0700, Paul Marquess wrote:

> Fixed in IO-Compress 2.104

Thanks.

Unfortunately something seems to not have worked as planned:

% wget  https://cpan.metacpan.org/authors/id/P/PM/PMQS/IO-Compress-2.104.tar.gz
[..]
% tar tfz IO-Compress-2.104.tar.gz|grep WeakDecrypt
IO-Compress-2.104/lib/IO/Compress/Zip/WeakDecrypt.pm

i.e. the 2.104 tarball on the CPAN still contains the (unchanged)
file.


Cheers,
gregor

-- 
 .''`.  https://info.comodo.priv.at -- Debian Developer https://www.debian.org
 : :' : OpenPGP fingerprint D1E1 316E 93A7 60A8 104D  85FA BB3A 6801 8649 AA06
 `. `'  Member VIBE!AT & SPI Inc. -- Supporter Free Software Foundation Europe
   `-

**Comment by pmqs** [comment]
> 

Damn! Just deleted it -- will try uploading again

**Comment by pmqs** [comment]
@gregoa  2.105 uploaded to CPAN. Shout of you find anything amiss.

thanks 
Paul

**Comment by gregoa** [comment]
On Sat, 09 Apr 2022 14:37:08 -0700, Paul Marquess wrote:

> @gregoa  2.105 uploaded to CPAN. Shout of you find anything amiss.

2.105 looks good, thank you!


Cheers,
gregor
