### ISSUE TITLE
Please document (POD, README, etc.) that IO::Compress also supports xz and lzma compression

### ISSUE THREAD

**Issue by xtaran** [pmqs/IO-Compress#4]
Besides the historic gzip, xz in the meanwhile seems the most often used compression method in the Linux. It definitely has superseeded bzip2 and I've never seen lzop really gaining a relevant market share.

Yet xz seems not yet supported by IO::Compress, especially not by IO::Uncompress::AnyUncompress whose name is a bit exaggerated given that it doesn't support the second most used compression.

**Comment by xtaran** [comment]
Just noticed that https://metacpan.org/release/IO-Compress-Lzma is also authored by you — which makes missing xz support even more unexpected. :-)

**Comment by xtaran** [comment]
Ok, the Debian package libio-compress-perl recommends libio-compress-lzma-perl which implies for me that there is actually support despite the readme and POD only mention gzip, bzip2 and lzop. So this seems primarily a documentation issue. Good! :-)

**Comment by pmqs** [comment]
Hey @xtaran 

In the POD for **IO::Uncompress::AnyUncompress** it mentions both **xz** and **lzma**.  Can you point me at part of the documentation are you looking at so I can review & update if needed please?

> **DESCRIPTION**
> This module provides a Perl interface that allows the reading of  files/buffers that have been compressed with a variety of compression  libraries.
>
> The formats supported are:
> * RFC 1950
> * RFC 1951 (optionally)
> * gzip (RFC 1952)
> * zip
> * bzip2
> * lzop
> * lzf
> * **lzma**
> * lzip
> * **xz**
>

**Comment by xtaran** [comment]
Sure:

https://github.com/pmqs/IO-Compress/blob/master/README#L18-L19
https://github.com/pmqs/IO-Compress/blob/master/lib/IO/Uncompress/AnyUncompress.pm#L273

There may be more, but these are the places I read first and which made me believe that there is no xz support.

**Comment by pmqs** [comment]
Thanks. I agree, those places need updated.

**Comment by pmqs** [comment]
Fixed in 126f7b9da97b572d0fb89a9bdcc190c5405c72b8

**Comment by xtaran** [comment]
Thanks!
