### ISSUE TITLE
Various modules of 2.105 distribution still declared version 2.104

### ISSUE THREAD

**Issue by ugexe** [pmqs/IO-Compress#43]
In the past it seems like the versions of the various modules have reflected that of the distribution itself. However, the latest release has mixed versions:

https://github.com/pmqs/IO-Compress/blob/42e028fc02bef2bd6a953911faf6af0d62550887/lib/IO/Compress/Base.pm#L23

https://github.com/pmqs/IO-Compress/blob/42e028fc02bef2bd6a953911faf6af0d62550887/lib/IO/Compress/Base/Common.pm#L14

**Comment by pmqs** [comment]
Yes, that is my usual way of working. In this instance I had to make a few minor changes after the main 2.103 release & didn't want the hassle of respinning everything again.

**Comment by oalders** [comment]
So, for purposes of pinning to a specific version should `IO::Compress::Base` be used? ie will this package always get a version bump?

**Comment by pmqs** [comment]
> So, for purposes of pinning to a specific version should `IO::Compress::Base` be used? ie will this package always get a version bump?

Yes. `Makefile.PL` uses `VERSION_FROM => 'lib/IO/Compress/Base.pm' to get the Version number.

This is a pretty unusual release I did because of time constraints. As soon as I can I want to get the versions all aligned again.

**Comment by oalders** [comment]
>As soon as I can I want to get the versions all aligned again

https://metacpan.org/dist/App-RewriteVersion has some helpful tools for this.

**Comment by pmqs** [comment]
All back in sync with 2,106
