### ISSUE TITLE
LICENSE File is missing

### ISSUE THREAD

**Issue by ranwitter** [pmqs/IO-Compress#53]
Automated SCA Tools (such a Blackduck) and Code Repositories (such a GitHub) can not identify; 

- Permissions (Commercial use, Modification, Distribution, Patent use, Private use)
- Limitations (Liability,Trademark use,Warranty)
- Conditions (License and copyright notice, State changes)

of Using this Module without including a LICENSE File in residing within the Code Basis.

**Comment by pmqs** [comment]
What are the implications of not having a LICENSE file? Do these tools then disallow the use of my code?

**Comment by ranwitter** [comment]
As a software developer we are obliged to submit a Software Bill of Materials to our Legal Department. We use SCA Tools to automate License Detection for all the FOSS Components. Having a License published together with the Code Basis will allow us to keep using IO::Compress Module as a FOSS Perl Module further. 

Thanks in Advance !

**Comment by ranwitter** [comment]
[Kind Explanation from Module Maintainer ](https://github.com/pmqs/IO-Compress/pull/52#issuecomment-1832585696)
