### ISSUE TITLE
No module matching dist name

### ISSUE THREAD

**Issue by haarg** [pmqs/IO-Compress#57]
This dist is named IO-Compress, but there is no matching IO::Compress module. While this is technically acceptable, it confuses various systems, including parts of perl core.

It would be more convenient to have an actual IO::Compress module. All it would need to contain would be a version number and some pod linking to the real modules contained in the dist.

**Comment by haarg** [comment]
There's nothing strictly incorrect with how things are now, but various automation tasks in perl core keep tripping over this. For example, the scripts that update perldelta keep trying to link to L<IO::Compress>, which doesn't exist. A number of releases of perl have gone out that had this broken link. And there isn't even a proper link it could be changed to. Obviously those automation scripts could be improved to handle this special case, but I think having a primary module to link to would be valuable in general.

**Comment by pmqs** [comment]
Closing. Change included in [2.213](https://github.com/pmqs/IO-Compress/releases/tag/v2.213)
