### ISSUE TITLE
DESTROY throws an exception when timing out

### ISSUE THREAD

**Issue by XSven** [pmqs/IO-Compress#58]
perl 5.14.2
IO::Uncompress::Gunzip 2.206
AIX 7300-02-02-2420

At our end it happens randomly that timing out this function

```
 sub _gunzip_file {
    my ( $filename ) = @_;

    my $gunzip = IO::Uncompress::Gunzip->new( $filename, { Append => 1, MultiStream => 1 } );
    my $buffer = '';
    1 while $gunzip->read( $buffer ) > 0;
    die "gunzip failed: $GunzipError\n" if $GunzipError;

    return $buffer;
  }
```
causes a DESTROY to raise the exception

`(in cleanup) HASH(0x113d9b678) at ...`

We are using `Sys::SigAction::timeout_call()` to implement the timeout. It is our guess that the DESTROY relates to the `$gunzip` object. Are you aware of such a phenomenon?

**Comment by pmqs** [comment]
No, not aware of this issue, although it is very likely that the DESTROY is coming from my code. 

Are you running a multi-threaded Perl application?

**Comment by pmqs** [comment]
To progress this I need to be able to reproduce the issue.

If you happen to have a small snippet of code that reproduces the issue I can take a look.

**Comment by XSven** [comment]
No I have no snippet of code to reproduce it but I have some educated guesses:

The `HASH(0x113d9b678)` in `(in cleanup) HASH(0x113d9b678) at ...` is the [TIMEOUT](https://metacpan.org/dist/Sys-SigAction/source/lib/Sys/SigAction.pm#L149) exception that interrupts the [DESTROY](https://metacpan.org/dist/IO-Compress/source/lib/IO/Uncompress/Base.pm#L1390). As an add-on problem a [reference count](https://perldoc.perl.org/perldiag#refcnt_dec:-fd-%25d%25s) panic exception is raised later too. Something is completely out of control if an alarm signal that is promoted to a TIMEOUT exception interrupts the DESTROY. Maybe this helps somehow.

**Comment by XSven** [comment]
No I am not running multi-threaded Perl application. The core of the application is based on `FCGI::ProcManager` that is forking child processes.

**Comment by nrdvana** [comment]
If you have a timeout that creates perl exceptions, they can occur inbetween *any* interpreted lines of code.  This includes code that runs during object destructors.  If the destructor is running automatically as part of a scope end, exceptions in that destructor do not interrupt the program flow.

```
perl -E '
  package DieObj {
    use v5.40;
    sub DESTROY { say "destroy"; die "whoops"; }
  }
  sub foo { my $x= bless {}, "DieObj"; undef $x }
  foo();
  say "did not die"'
```

So, basically you can't reliably combine signal-induced exceptions with object destructors.

The reference count panic is a different problem and probably represents a bug somewhere.

**Comment by Leont** [comment]
You're using unsafe signals in `Sys::SigAction`. That means you get to keep both halves if you get segfaults or other errors like perl panics. You should probably rewrite your code to not need `Sys::SigAction`.

**Comment by nrdvana** [comment]
@XSven actually Leont's answer is more on-point in that the module Sys::SigAction is introducing fundamental interpreter breakage in how it handles signals, so when using that module you should be prepared to deal with low-level crashes.

For the safe version, e.g.
```
   local $SIG{ALRM}= sub { die "timeout" };
   eval {
     alarm 10;
     ...
   };
   alarm 0;

```
that can work in narrow controlled situations, but if you are calling into arbitrary code there's no guarantee that the module won't be in the middle of its own `eval` when the signal arrives, or like this case be running a destructor that likewise loses the exception.

If you want a one-size-fits-all solution that can interrupt arbitrary perl code at a timeout, you pretty much need to put the task in a child process and kill the child process from the parent.  The cleaner route is to implement your entire program in non-blocking event-driven style, but that's often too much rewrite to consider for existing code.

It's only slightly related, but for more insight on the problem check out my list of caveats in [IO::SocketAlarm](https://metacpan.org/pod/IO::SocketAlarm#DESCRIPTION), which I just updated to mention this destructor problem.

**Comment by Leont** [comment]
> Thanks @Leont, @nrdvana I will do! So there is no way in perl to implement a timeout action that is based on an alarm-signal-induced exception?

Safe signals would work with pure perl modules (assuming no eval is getting in the way) and some XS modules but they'd have to be adapted to it (), and if they go too deep into C library then it probably still wouldn't work,

Generally speaking, this is a poor approach though, but perhaps we should first take a step back and ask you what you're actually trying to achieve. You shouldn't need a timeout on a gzip handle ordinarily; why would you be waiting so long.
