### ISSUE TITLE
[doc] typos in perl-5.40.0/cpan/IO-Compress/bin/streamzip

### ISSUE THREAD

**Issue by sobrado8086** [pmqs/IO-Compress#59]
There are a few typos in perl-5.40.0/cpan/IO-Compress/bin/streamzip.  See attached diff for details.
[streamzip.patch](https://github.com/user-attachments/files/17735938/streamzip.patch)

**Comment by pmqs** [comment]
Thanks for the patch. Changes included  in change e70223ed043fb11c0dcaad3204286ee0a263f58e

**Comment by sobrado8086** [comment]
Thanks a lot for managing this issue.
