### ISSUE TITLE
Header Error: Minimum header size is 10 bytes

### ISSUE THREAD

**Issue by XSven** [pmqs/IO-Compress#60]
I have a _.gz_ compressed file that I am applying the following script to:

```
#!/usr/bin/env perl

use strict;
use warnings;

use IO::Uncompress::Gunzip qw( $GunzipError );

sub _gunzip_file {
  my ( $filename ) = @_;

  my $gunzip = IO::Uncompress::Gunzip->new( $filename, { Append => 1, MultiStream => 1 } );
  my $buffer = '';
  1 while $gunzip->read( $buffer ) > 0;
  die "gunzip failed: $GunzipError\n" if $GunzipError;

  return $buffer;
}

_gunzip_file $ARGV[0];
```

I am using `IO::Uncompress::Gunzip` 2.213 and different versions of perl 5.14.2, 5.14.4, 5.22.3. My operating system is AIX 7300-02-02-2420. I am getting all the time the same error

`Header Error: Minimum header size is 10 bytes`

I have checked the integrity of the _.gz_ file using `gunzip -t` and it is ok. I can even uncompress it successfully not using perl. What is causing the error. The first 10 bytes are

`1f 8b 08 08 00 0c 23 67 02 03`

**Comment by pmqs** [comment]
Hmmm, not sure what is going on there. Those bytes look ok.

I notice that you have `MultiStream` enabled. Perhaps there is something amiss with a second, or subsequent, compressed stream -- assuming there is one. The other alternative is there isn't a second stream and you have trailing junk data. Mind you, if there was trailing data the command line `gunzip`  should report it.

If you disable `MultiStream` does it uncompress the first stream correctly?

**Comment by XSven** [comment]
Yes it does, but I am sure that I have used the MultiStream option because it was your suggestion to overcome another issue. I will search it now in the issue list.

**Comment by pmqs** [comment]
Any chance you can create a gzip file that triggers the issue that can be uploaded here?

**Comment by XSven** [comment]
That is the output
```
File 'S3_006924.20241031054800+SOAP_RESPONSE.xml.gz' is 692 bytes
* 1: tell 0 eof:  Trailing 0 Offset 0
  uncompressed length is 1346
* 2: tell 692 eof: 1 Trailing 1 Offset 691
Cannot create gunzip: Header Error: Minimum header size is 10 bytes at stream.pl line 23.
```
I will now examine the bytes around the last offset value that is 691.

**Comment by XSven** [comment]
```
c8 7e 03 e8 51 da 87 42 05 00 00 00
                              ^
                              691 byte position
```

**Comment by pmqs** [comment]
It appears that your gzip file contains a single RFC1950 stream, but has an extra trailing null byte at the end of the file. That means it isn't strictly conformant with RFC1952, although the gzip/gunzip man page says this about trailing NULLs

> When  writing compressed data to a tape, it is generally necessary to pad the output with zeroes up to a block boundary. When the data is read and the whole block is passed to gunzip for decompression, gunzip detects that there  is extra trailing garbage after the compressed data and emits a warning by default.

When you are uncompressing the gzipped data, do you just want it all uncompressed into a single buffer, or do you want the stream uncompress it and manipulate each uncompressed chunk?

If you just want to uncompress to a buffer, you could try using the one-shot interface, like below. The behaviour of the `gunzip` function is slightly different from the OO interface -- it shouldn't complain about trailing data

```perl
use IO::Uncompress::Gunzip qw(:all) ;

my $filename = $ARGV[0];

my $buffer = '';

gunzip $filename => \$buffer, Multistream => 1, Transparent => 0
    or die "Error decompressing '$filename': $GunzipError\n";

print $buffer;
```

**Comment by XSven** [comment]
I want it all uncompressed into a single buffer. Your proposal works.

**Comment by pmqs** [comment]
Good to hear.

Closing this issue. Reopen, or create a new issue, if you still have any problems.
