### ISSUE TITLE
Header Error: Bad Magic

### ISSUE THREAD

**Issue by XSven** [pmqs/IO-Compress#62]
This is a similar issue like [GH60](https://github.com/pmqs/IO-Compress/issues/60). The exception message is different. The integrity of the _.gz_ file was again checked with  `gunzip -t`. Unzippig works if `MultiStream` is off/false.

**Comment by pmqs** [comment]
To get a `Bad Magic` error with my code in the scenario you describe  the following must happen:

1. The first gzip stream is fine.
2. There needs to be 10, or more, bytes after the end of the first compressed data stream
3. The first two bytes of the appended data must not be 0x1f 0x8B.

Can you run the script I included on #60 and see if the trailing bytes are all null characters please?

**Comment by XSven** [comment]
This is the result
```
File 'x.gz' is 789 bytes
* 1: tell 0 eof:  Trailing 0 Offset 0
  uncompressed length is 1899
* 2: tell 789 eof: 1 Trailing 2 Offset 787
Cannot create gunzip: Header Error: Bad Magic at stream.pl line 23.
```
```
f7 1f d6 6b 07 00 00 00 00
                  ^
                  787
```

I have used your script proposal [2509352829](https://github.com/pmqs/IO-Compress/issues/60#issuecomment-2509352829) and this solves the bad magic problem too. Is this the way to go?

**Comment by pmqs** [comment]
> ...
> I have used your script proposal [2509352829](https://github.com/pmqs/IO-Compress/issues/60#issuecomment-2509352829) and this solves the bad magic problem too. Is this the way to go?

Yes, it is.
