### ISSUE TITLE
Information on zipdetails

### ISSUE THREAD

**Issue by perlpunk** [pmqs/IO-Compress#8]
Hi,

this distribution comes with its own version of `zipdetails`, which is already delivered with perl core.
I stumbled upon this while maintaining the perl modules repository for openSUSE.

The problem is that when another module depends on perl and IO::Compress (like IO::Compress::Lzma), there is a conflict between the script delivered with perl and the one from this module.
One solution could be renaming it to `/usr/bin/zipdetails-IO-Compress` in [our spec file](https://build.opensuse.org/package/show/devel:languages:perl/perl-IO-Compress).
What do you think?

**Comment by pmqs** [comment]
Hey @perlpunk the problem with your suggestion is that this instance of `IO-Compress` is exactly the same as the one that ships with perl. All changes made here ripple straight into perl code.

If I changed the name of `zipdetails`, the change would end up in perl core, and you would be back to square one.

**Comment by perlpunk** [comment]
Yes, sorry, I did not mean it should be renamed on CPAN, but in our spec file. I edited my comment.
However, if it is the same script as in perl core, then I guess we can just delete it in our spec file.

**Comment by pmqs** [comment]
Aaah, OK. If it means you only install `zipdetails` once, then that the way to go.

One thing to consider though, if there is an update to `zipdetails`, it will be available in this module well before it works its way into a shipping version of Perl. So perhaps you should remove it from the perl spec file instead?

**Comment by perlpunk** [comment]
Hm, I see.
I guess in that case we need to make both available (`zipdetails` works without IO::Compress installed, so just removing it is probably not a good idea).
Thanks for the info!

**Comment by pmqs** [comment]
No problem. 

I'll close this ticket. Please shout if you need anything else.
